version: "2"
services:
  app:
    container_name: product-microservice
    restart: always
    build: .
    ports:
      - "3000:${PORT:-3000}"
    links: 
      - mongodb
    environment:
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017
      PORT: ${PORT:-3000}
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
